### ISSUE TITLE
Add chat list and chat into one page

### ISSUE THREAD

**Issue by EteimZ** [EteimZ/lingo#2]
Currently there are two pages that handle the process of chatting and listing of chats. Rather than having multiple pages let it be consolidated into one page. On large screens it would be displayed this way:

![Online_offline_lingo(2)](https://github.com/EteimZ/lingo/assets/45427673/c297466f-a24f-4c12-88d9-1be7585a1f1b)

On smaller screens it would be displayed this way:

![Online_offline_lingo(3)](https://github.com/EteimZ/lingo/assets/45427673/8ed109a9-0d26-4cf0-b062-48d62b86a0ac)

**Comment by Ebiladou** [comment]
I am willing to resolve this issue.

Following your design structure, my approach would be to design a consolidated page that integrates chat listing and individual chat views like the twitter web application direct message UI, and refactor the codebase. I'll start working on this immediately and should have a draft solution ready within the week. 

If you have any specific preference(s) for how the consolidated page should function, please share.

**Comment by EteimZ** [comment]
Hi @Ebiladou  thanks for expressing interest in working on this issue.

I wouldn't say if I have any preference but it would be best if you stick with Chakra UI components. The perfect one will be to use Chakra's [grid component](https://chakra-ui.com/docs/components/grid).

**Comment by Ebiladou** [comment]
Noted.
